### ISSUE TITLE
Error when trying to generate frame with frame.c

### ISSUE THREAD

**Issue by LucasMahieu** [meninge/moineau#1]
see the error : 

$> python frames.py 10 test-images-idx3-ubyte train-labels-idx1-ubyte
Traceback (most recent call last):
  File "frames.py", line 67, in <module>
    write_frames_array(sys.argv[2], int(sys.argv[1]))
  File "frames.py", line 42, in write_frames_array
    frames.write("%s, " % hex(ord(data.read(1))))
TypeError: ord() expected a character, but string of length 0 found

**Comment by LucasMahieu** [comment]
bad number of image in the ubyte file
